organization: hashi-demos-apj
workspace_name: aws-future-app-example
agent_pool_name: AaronPool
vcs_repo:
  identifier: hashicorp-demo-lab/app-the-future-aws
  branch: main
  ingress_submodules: null
  oauth_token_id: ot-EEzS6zKkh8tEBC7o
